#!/usr/bin/env sh

usage ()
{
    echo 'Usage: letsencrypt_connect domainname.example.com'
    exit
}

if [ "$#" -ne 1 ]
then
  usage
fi

DOMAIN=$1
SSL_DIR="/etc/nginx/ssl"
LETSENCRYPT_DIR="$SSL_DIR/live/$DOMAIN"

if [ -d $LETSENCRYPT_DIR ]; then
    rm $SSL_DIR/ssl.crt
    rm $SSL_DIR/ssl.key

    ln -s $LETSENCRYPT_DIR/fullchain.pem $SSL_DIR/ssl.crt
    ln -s $LETSENCRYPT_DIR/privkey.pem $SSL_DIR/ssl.key

    echo 'Domain is ready to be served via LetsEncrypt!'
    echo 'To reload nginx, please run:'
    echo '  docker-compose kill -s SIGHUP nginx'
    echo ' '
    exit
else
    echo "Domain name $DOMAIN is not set up with LetsEncrypt yet."
    exit 1
fi

